Define Tx and packagedTx in proto. Ref#47
Plane-walker/Okeanos pull request #58
Opened 2021-12-10 08:48 UTC by liuxueye

Define Tx and packagedTx in proto. Renew  dci_pb2.py & dci_pb2_grpc.py file .Please review the two files for errors.

close #47

2021-12-11 02:40 UTC, Plane-walker requested changes

2021-12-11 02:40 UTC, Plane-walker commented on dock/interface/dci_pb2_grpc.py
> +from dci import dci_pb2 as dci_dot_dci__pb2
This should be
`import dci_pb2 as dci_dot_dci__pb2`

2021-12-11 05:38 UTC, Bay1997 approved these changes

2021-12-11 06:05 UTC, Plane-walker approved these changes

2021-12-13 03:16 UTC, quincysky approved these changes

2021-12-13 14:54 UTC, merged